/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import pojosKidney.Patient;
import Utilities.Utilities;
import static Utilities.Utilities.AssignementsOptions;
import static Utilities.Utilities.IDsOptionsCollection;
import static Utilities.Utilities.IDsParametersCollection;
import pojosKidney.PatientSimple;

/**
 *
 * @author carmen
 */

public class Questionary extends javax.swing.JFrame {
    String [] quest= new String [8];
    boolean [] answ= new boolean[8];
    public static Patient p2 = new Patient();
    int cont=0;
    private int ID;

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }      
    /**
     * Creates new form FirstWindow
     */
    public Questionary() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.progBar.setValue(0);
        this.BackBut.setVisible(false);
        this.error.setVisible(false);
        quest[0]= "Was the donor alive?";
        quest[1]= "Was the organ more than 19 hours out of the organisim?";
        quest[2]= "Was the transplan more than two weeks ago? ";
        quest[3]= "Was the creatinine of the donor more than 2.5?";
        quest[4]= "Does the patient present HLA Incompatibility?";
        quest[5]= "Does the patient present Fibrinoid Necrosis? ";
        quest[6]= "Does the patient present IL10 and TNF?";
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        panelP = new javax.swing.JPanel();
        error = new javax.swing.JLabel();
        BackBut = new javax.swing.JButton();
        YesBut = new javax.swing.JRadioButton();
        NoBut = new javax.swing.JRadioButton();
        questionsText = new javax.swing.JLabel();
        NextBut = new javax.swing.JButton();
        progBar = new javax.swing.JProgressBar();
        porbText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(0, 51, 153));

        panelP.setBackground(new java.awt.Color(231, 243, 255));

        error.setFont(new java.awt.Font("STKaiti", 0, 14)); // NOI18N
        error.setForeground(new java.awt.Color(0, 0, 204));
        error.setText("You have to select one option!");

        BackBut.setBackground(new java.awt.Color(0, 51, 153));
        BackBut.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        BackBut.setText("Back");
        BackBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 153), null, null));
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        YesBut.setFont(new java.awt.Font("STKaiti", 0, 13)); // NOI18N
        YesBut.setText("Yes");
        YesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesButActionPerformed(evt);
            }
        });

        NoBut.setFont(new java.awt.Font("STKaiti", 0, 13)); // NOI18N
        NoBut.setText("No");
        NoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoButActionPerformed(evt);
            }
        });

        questionsText.setFont(new java.awt.Font("STKaiti", 1, 18)); // NOI18N
        questionsText.setText("Was the donor alive?");
        questionsText.setToolTipText("");

        NextBut.setBackground(new java.awt.Color(0, 51, 153));
        NextBut.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        NextBut.setText("Next");
        NextBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 153), null, null));
        NextBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButActionPerformed(evt);
            }
        });

        porbText.setFont(new java.awt.Font("STKaiti", 1, 18)); // NOI18N
        porbText.setText("0%");
        porbText.setToolTipText("");

        javax.swing.GroupLayout panelPLayout = new javax.swing.GroupLayout(panelP);
        panelP.setLayout(panelPLayout);
        panelPLayout.setHorizontalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPLayout.createSequentialGroup()
                        .addComponent(questionsText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(278, 278, 278))
                    .addGroup(panelPLayout.createSequentialGroup()
                        .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelPLayout.createSequentialGroup()
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(porbText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(YesBut)
                        .addGap(18, 18, 18)
                        .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NextBut, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoBut))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        panelPLayout.setVerticalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPLayout.createSequentialGroup()
                        .addComponent(progBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(questionsText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(porbText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesBut)
                    .addComponent(NoBut))
                .addGap(19, 19, 19)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextBut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        cont --;
        if(YesBut.isSelected()||NoBut.isSelected()){
            error.setVisible(false);
            if(YesBut.isSelected()){
               YesBut.setSelected(false);
            }else{
              NoBut.setSelected(false);
            }
        }
        this.questionsText.setText(quest[cont]); 
        this.progBar.setValue((int)((cont*100)/7));
        this.porbText.setText(((cont*100)/7)+ "%");
        if(cont==0){
            this.BackBut.setVisible(false);
        }
    }//GEN-LAST:event_BackButActionPerformed

    private void YesButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesButActionPerformed
        error.setVisible(false);
        NoBut.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_YesButActionPerformed

    private void NoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoButActionPerformed
        error.setVisible(false);
        YesBut.setSelected(false);    // TODO add your handling code here:
    }//GEN-LAST:event_NoButActionPerformed

    private void NextButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButActionPerformed
       if(YesBut.isSelected()||NoBut.isSelected()){
            error.setVisible(false);
            if(YesBut.isSelected()){
               answ[cont]= true;
               YesBut.setSelected(false);
            }else{
              answ[cont]= false;
              NoBut.setSelected(false);
            }
            cont++;
            this.progBar.setValue((int)((cont*100)/7));
            this.porbText.setText(((cont*100)/7)+ "%");
            this.BackBut.setVisible(true);
            this.questionsText.setText(quest[cont]); 
        }else{
            error.setVisible(true);
        }
       if(cont==6){
           this.NextBut.setText("Finish");
           //aqui deberiamos sumar uno al contador de tests del PatientSimple
       }else{
            this.NextBut.setText("Next");
       }
       if(cont==7){
           System.out.println("Estamos ya introduciendo ha terminado no??");
           System.out.println(answ[0]);
           p2 = Utilities.introd(answ);
           
           //Obtaining IDsOptions:        
           String [] options = AssignementsOptions(p2);
           int[] IDoptions = IDsOptionsCollection(options, FirstWindow.patientManager);
           
           //Obtaining IDsParameters:
           int[] IDParameters = IDsParametersCollection(FirstWindow.patientManager);
           
           Solution rd = new Solution();
           rd.setID(ID);
           rd.setIDsOptions(IDoptions);
           rd.setIDsParameters(IDParameters);
           this.setVisible(false);
           rd.setVisible(true);
       }
    }//GEN-LAST:event_NextButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JButton NextBut;
    private javax.swing.JRadioButton NoBut;
    private javax.swing.JRadioButton YesBut;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel error;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panelP;
    private javax.swing.JLabel porbText;
    private javax.swing.JProgressBar progBar;
    private javax.swing.JLabel questionsText;
    // End of variables declaration//GEN-END:variables
}
