/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Cristina
 */
public class ShowHistory extends javax.swing.JPanel {
    private int ID;

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }   
    /**
     * Creates new form ShowHistory
     */
    public ShowHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        panelP = new javax.swing.JPanel();
        back_but = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPatient = new javax.swing.JList<>();
        showTest_but = new javax.swing.JButton();
        go_but = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        panelP.setBackground(new java.awt.Color(208, 226, 217));

        back_but.setBackground(new java.awt.Color(0, 102, 0));
        back_but.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        back_but.setText("<-");
        back_but.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 102, 255), null, null));
        back_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_butActionPerformed(evt);
            }
        });

        ListPatient.setFont(new java.awt.Font("STKaiti", 0, 12)); // NOI18N
        ListPatient.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ListPatient);

        showTest_but.setBackground(new java.awt.Color(0, 102, 0));
        showTest_but.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        showTest_but.setText("Show tests");
        showTest_but.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 102, 255), null, null));
        showTest_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTest_butActionPerformed(evt);
            }
        });

        go_but.setBackground(new java.awt.Color(0, 102, 0));
        go_but.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        go_but.setText("GO!");
        go_but.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 102, 255), null, null));
        go_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPLayout = new javax.swing.GroupLayout(panelP);
        panelP.setLayout(panelPLayout);
        panelPLayout.setHorizontalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelPLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(back_but, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(go_but, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(panelPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(showTest_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPLayout.setVerticalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(showTest_but, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_but, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(go_but, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("STKaiti", 1, 18)); // NOI18N
        jLabel1.setText("Tests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void go_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_butActionPerformed
        String Ntest = this.ListPatient.getSelectedValue();
        int position = Ntest.indexOf(" ");
        int test = Utilities.Utilities.convertInt(Ntest.substring(position, Ntest.length()));
        String[] tests = Utilities.Utilities.returnPatient(FirstWindow.patientSimple.getID(), test, FirstWindow.patientManager);
        
        // coger paciente por nombre o por id a lo mejor si lo enseñamos

        //si cogido--> pasamos a un menu para ver que quiere hacer
        /*  if (received) {
            PatientInformation rd = new PatientInformation();
            this.setVisible(false);
            rd.setVisible(true);
        } // TODO add your handling code here:*/
    }//GEN-LAST:event_go_butActionPerformed

    private void back_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_butActionPerformed
        FirstWindow rd = new FirstWindow();
        this.setVisible(false);
        rd.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_back_butActionPerformed

    private void showTest_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTest_butActionPerformed
        DefaultListModel<String> model2 = new DefaultListModel<>();
        JList<String> list = new JList<>(model2);

        //take names from the database
        int Ntest = FirstWindow.patientSimple.Ntest;
        
        //ArrayList<PatientSimple> patientList = new ArrayList<>();
        
        for (int i = 0; i < Ntest; i++) {
            model2.addElement("Test " + i);         
        }
        this.ListPatient.setModel(model2);   // TODO add your handling code here:
    }//GEN-LAST:event_showTest_butActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListPatient;
    private javax.swing.JButton back_but;
    private javax.swing.JButton go_but;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelP;
    private javax.swing.JButton showTest_but;
    // End of variables declaration//GEN-END:variables
}
